# Generated by Django 5.1.4 on 2024-12-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccountManager', '0004_alter_user_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('resident', 'Resident')], default='resident', max_length=10),
        ),
    ]
