# Generated by Django 5.1.4 on 2024-12-25 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentManager', '0001_initial'),
        ('UserAccountManager', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='ApartmentManager.apartmentdetails'),
        ),
    ]
