# Generated by Django 5.1.4 on 2024-12-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(max_length=150)),
            ],
        ),
    ]
