# Generated by Django 5.1.4 on 2024-12-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentManager', '0002_watersensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersensor',
            name='pump_on',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
